# -*- coding: utf-8 -*-
"""Image_ProcessingEx2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YUfRoLkou26GrkxzIhVvLorAlws1HD7_
"""

import sys
import cv2

# image name as  first arg
data=sys.argv[1]

# image read
img=cv2.imread(data,1)

print(img)

# shape
print(img.shape)

# height, width, colorchannel

# to show the image
cv2.imshow('windowname',img)
# holding window for infinite time
cv2.waitKey(0)

